### PR TITLE
Cfa (Issue #24)

### PR DESCRIPTION
**Pull request by nickhaf**
Proposition for CFA taxon. Just a draft right now - let me know what you think about the general concept. Idea is to represent each factor as a vector element. Added a little example so you get the idea. Might get a little bit overwhelming with many factors - added a first plausibility check for vector lengths.

### CODE REVIEW

**Comment by nickhaf** [comment]
Note: Tried to change SEM.jl dependency to StenoGraphs dependency (by using rm StructuralEquationModels in package mode, after either "] activate ." or "] activate ./test". However, got some doctest errors afterwards. 
Also have a weird error in the CFA testset, two expressions that should be the same are not the same. I will look at it the next days.

**Comment by nickhaf** [comment]
Since this morning I got an issue with the record function (even though there were no changes since yesterday): 

┌ Warning: You really should supply an ID. May we suggest (from DOI): 8f1713c9-482b-58cb-8ed4-128c03e9dafb
└ @ Taxonomy c:\Users\hafiznij\Documents\GitHub\Taxonomy.jl\src\record.jl:19
ERROR: Can not reach DOI service. Maybe internet connection down?
Stacktrace:
 [1] error(s::String)
   @ Base .\error.jl:33
 [2] interpret_status
   @ c:\Users\hafiznij\Documents\GitHub\Taxonomy.jl\src\metadata\meta.jl:176 [inlined]
 [3] interpret_status
   @ c:\Users\hafiznij\Documents\GitHub\Taxonomy.jl\src\metadata\meta.jl:180 [inlined]
 [4] json(location::UsualDOI{String, Missing})
   @ Taxonomy c:\Users\hafiznij\Documents\GitHub\Taxonomy.jl\src\metadata\meta.jl:225
 [5] MetaData(location::UsualDOI{String, Missing})
   @ Taxonomy c:\Users\hafiznij\Documents\GitHub\Taxonomy.jl\src\metadata\meta.jl:251
 [6] Record(; rater::String, id::Missing, location::UsualDOI{String, Missing}, meta::Missing, taxons::Vector{Factor}, spec::Bool, data::Bool)
   @ Taxonomy c:\Users\hafiznij\Documents\GitHub\Taxonomy.jl\src\record.jl:30
 [7] top-level scope
   @ c:\Users\hafiznij\Documents\GitHub\Taxonomy.jl\docs\src\tutorials\start.md:16

**Comment by nickhaf** [comment]
Still got the ERROR: Can not reach DOI service. Maybe internet connection down?

**Comment by aaronpeikert** [comment]
This really means that the service is not reachable. Nothing in your code or so can account for that. Its thrown from here:

https://github.com/StructuralEquationModels/Taxonomy.jl/blob/2b713056ef6a42a8df8b2454cf8eb5f65713aeaa/src/metadata/meta.jl#L166-L178

**Review by aaronpeikert — APPROVED** [review]
Perfekt. Thanks

**Pull request merged**
